export const TEST_DIALOG = "test";
export const ITEM_CREATE_DIALOG = "ITEM_CREATE_DIALOG";
export const ITEM_DELETE_DIALOG = "ITEM_DELETE_DIALOG";
export const ITEM_EDIT_DIALOG = "ITEM_EDIT_DIALOG";
export const USER_CREATE_DIALOG = "USER_CREATE_DIALOG";
export const USER_DELETE_DIALOG = "USER_DELETE_DIALOG";
export const USER_EDIT_DIALOG = "USER_EDIT_DIALOG";